// =====================================================
//  Dynamic Business Needs Configuration — AI Emply Step 2
// =====================================================

export interface BusinessNeed {
  id: string;
  label: string;
  description: string;
  icon: string;
  industries: string[];
  supportedAgents: string[];
  priority?: number;
}

export const businessNeedsCatalog: BusinessNeed[] = [
  // ── EDUCATION ───────────────────────────────────────────────
  {
    id: 'student_enquiries',
    label: 'Student Enquiries',
    description: 'Answer routine student and parent questions instantly 24/7.',
    icon: 'chat',
    industries: ['education'],
    supportedAgents: ['admission_counselor', 'student_support_agent'],
    priority: 10,
  },
  {
    id: 'admissions',
    label: 'Admissions Guidance',
    description: 'Guide prospective students through eligibility and application steps.',
    icon: 'grad_cap',
    industries: ['education'],
    supportedAgents: ['admission_counselor'],
    priority: 10,
  },
  {
    id: 'course_info',
    label: 'Course Information',
    description: 'Provide curriculum, syllabus, and program details on demand.',
    icon: 'doc',
    industries: ['education'],
    supportedAgents: ['admission_counselor', 'student_support_agent'],
    priority: 9,
  },
  {
    id: 'lead_capture_edu',
    label: 'Lead Capture',
    description: 'Collect student contact information and qualification criteria.',
    icon: 'funnel',
    industries: ['education'],
    supportedAgents: ['admission_counselor', 'lead_qualification_agent'],
    priority: 9,
  },
  {
    id: 'student_followups',
    label: 'Student Follow-ups',
    description: 'Automate follow-up reminders and enrollment check-ins.',
    icon: 'phone',
    industries: ['education'],
    supportedAgents: ['admission_counselor', 'lead_qualification_agent'],
    priority: 8,
  },
  {
    id: 'parent_enquiries',
    label: 'Parent Enquiries',
    description: 'Address parent concerns regarding safety, hostel, and academics.',
    icon: 'user',
    industries: ['education'],
    supportedAgents: ['admission_counselor', 'student_support_agent'],
    priority: 7,
  },
  {
    id: 'counseling_booking',
    label: 'Counseling & Campus Tours',
    description: 'Schedule 1-on-1 counseling calls or on-campus visit slots.',
    icon: 'calendar',
    industries: ['education'],
    supportedAgents: ['admission_counselor', 'appointment_coordinator'],
    priority: 8,
  },
  {
    id: 'fee_enquiries',
    label: 'Fee & Scholarship Enquiries',
    description: 'Share fee structures, payment milestones, and merit aid criteria.',
    icon: 'dollar',
    industries: ['education'],
    supportedAgents: ['admission_counselor'],
    priority: 8,
  },
  {
    id: 'student_support',
    label: 'Student Support',
    description: 'Provide enrolled students with campus resources, schedules, and FAQs.',
    icon: 'support',
    industries: ['education'],
    supportedAgents: ['student_support_agent'],
    priority: 7,
  },

  // ── RESTAURANT ──────────────────────────────────────────────
  {
    id: 'rest_customer_enquiries',
    label: 'Customer Enquiries',
    description: 'Handle incoming guest questions regarding cuisine, parking, and policies.',
    icon: 'chat',
    industries: ['restaurant'],
    supportedAgents: ['restaurant_concierge', 'customer_support_agent'],
    priority: 10,
  },
  {
    id: 'table_reservations',
    label: 'Table Reservations',
    description: 'Book table slots, gather party sizes, and collect seating preferences.',
    icon: 'calendar',
    industries: ['restaurant'],
    supportedAgents: ['restaurant_concierge', 'reservation_assistant'],
    priority: 10,
  },
  {
    id: 'menu_questions',
    label: 'Menu & Dietary Inquiries',
    description: 'Explain dishes, specials, and vegetarian, vegan or allergen options.',
    icon: 'doc',
    industries: ['restaurant'],
    supportedAgents: ['restaurant_concierge'],
    priority: 9,
  },
  {
    id: 'opening_hours',
    label: 'Opening Hours & Location',
    description: 'Share operational hours, holiday schedules, and directions.',
    icon: 'map',
    industries: ['restaurant'],
    supportedAgents: ['restaurant_concierge', 'customer_support_agent'],
    priority: 8,
  },
  {
    id: 'order_support',
    label: 'Takeout & Delivery Support',
    description: 'Guide guests through online ordering links and pickup information.',
    icon: 'bag',
    industries: ['restaurant'],
    supportedAgents: ['restaurant_concierge', 'customer_support_agent'],
    priority: 8,
  },
  {
    id: 'customer_feedback',
    label: 'Customer Feedback & Reviews',
    description: 'Collect dining feedback and handle guest ratings proactively.',
    icon: 'star',
    industries: ['restaurant'],
    supportedAgents: ['restaurant_concierge', 'customer_support_agent'],
    priority: 7,
  },
  {
    id: 'event_enquiries',
    label: 'Private Events & Parties',
    description: 'Capture group bookings, private dining requests, and guest requirements.',
    icon: 'user',
    industries: ['restaurant'],
    supportedAgents: ['restaurant_concierge', 'lead_qualification_agent'],
    priority: 8,
  },
  {
    id: 'catering_enquiries',
    label: 'Catering Inquiries',
    description: 'Collect dates, headcount, and budget for outside catering requests.',
    icon: 'funnel',
    industries: ['restaurant'],
    supportedAgents: ['restaurant_concierge', 'lead_qualification_agent'],
    priority: 7,
  },
  {
    id: 'rest_followups',
    label: 'Guest Follow-ups',
    description: 'Send booking confirmations and post-dining thank-you notes.',
    icon: 'phone',
    industries: ['restaurant'],
    supportedAgents: ['restaurant_concierge', 'reservation_assistant'],
    priority: 7,
  },

  // ── HEALTHCARE ──────────────────────────────────────────────
  {
    id: 'appointment_booking_health',
    label: 'Appointment Booking',
    description: 'Coordinate doctor appointments, specialist slots, and consultation times.',
    icon: 'calendar',
    industries: ['healthcare'],
    supportedAgents: ['appointment_coordinator'],
    priority: 10,
  },
  {
    id: 'appointment_reminders',
    label: 'Appointment Reminders',
    description: 'Automate confirmation messages to reduce patient no-shows.',
    icon: 'phone',
    industries: ['healthcare'],
    supportedAgents: ['appointment_coordinator'],
    priority: 9,
  },
  {
    id: 'patient_enquiries',
    label: 'Patient Enquiries',
    description: 'Answer questions about clinic locations, accepted insurance, and visits.',
    icon: 'chat',
    industries: ['healthcare'],
    supportedAgents: ['patient_info_assistant', 'appointment_coordinator'],
    priority: 10,
  },
  {
    id: 'clinic_info',
    label: 'Clinic & Department Information',
    description: 'Provide specialist directories, working hours, and facility details.',
    icon: 'doc',
    industries: ['healthcare'],
    supportedAgents: ['patient_info_assistant'],
    priority: 8,
  },
  {
    id: 'service_info_health',
    label: 'Service & Treatment Overview',
    description: 'Explain available clinical procedures and routine wellness checks.',
    icon: 'support',
    industries: ['healthcare'],
    supportedAgents: ['patient_info_assistant'],
    priority: 8,
  },
  {
    id: 'followup_coordination',
    label: 'Follow-up Coordination',
    description: 'Assist patients in booking routine follow-ups and checkup visits.',
    icon: 'calendar',
    industries: ['healthcare'],
    supportedAgents: ['appointment_coordinator'],
    priority: 8,
  },
  {
    id: 'reception_support',
    label: 'Digital Reception Support',
    description: 'Act as a 24/7 front-desk assistant answering routine patient inquiries.',
    icon: 'user',
    industries: ['healthcare'],
    supportedAgents: ['patient_info_assistant', 'appointment_coordinator'],
    priority: 9,
  },
  {
    id: 'faq_health',
    label: 'Frequently Asked Questions',
    description: 'Address visiting hours, parking, cashless claims, and lab timings.',
    icon: 'doc',
    industries: ['healthcare'],
    supportedAgents: ['patient_info_assistant'],
    priority: 7,
  },

  // ── REAL ESTATE ─────────────────────────────────────────────
  {
    id: 'property_enquiries',
    label: 'Property Enquiries',
    description: 'Answer questions on configurations, floor plans, and pricing.',
    icon: 'doc',
    industries: ['real_estate'],
    supportedAgents: ['property_enquiry_agent', 'viewing_coordinator'],
    priority: 10,
  },
  {
    id: 'lead_capture_re',
    label: 'Buyer Lead Capture',
    description: 'Collect buyer contact details, budgets, and location preferences.',
    icon: 'funnel',
    industries: ['real_estate'],
    supportedAgents: ['property_enquiry_agent', 'lead_qualification_agent'],
    priority: 10,
  },
  {
    id: 'site_visits',
    label: 'Site Visit Scheduling',
    description: 'Book on-site property tours and coordinate agent showings.',
    icon: 'calendar',
    industries: ['real_estate'],
    supportedAgents: ['viewing_coordinator', 'property_enquiry_agent'],
    priority: 9,
  },
  {
    id: 'buyer_qualification',
    label: 'Buyer Qualification',
    description: 'Screen buyer timelines, funding status, and property requirements.',
    icon: 'user',
    industries: ['real_estate'],
    supportedAgents: ['lead_qualification_agent', 'property_enquiry_agent'],
    priority: 9,
  },
  {
    id: 'rental_enquiries',
    label: 'Rental Enquiries',
    description: 'Handle tenant inquiries, lease terms, and move-in dates.',
    icon: 'chat',
    industries: ['real_estate'],
    supportedAgents: ['property_enquiry_agent'],
    priority: 8,
  },
  {
    id: 're_followups',
    label: 'Client Follow-ups',
    description: 'Follow up with property seekers and share updated project brochures.',
    icon: 'phone',
    industries: ['real_estate'],
    supportedAgents: ['lead_qualification_agent', 'property_enquiry_agent'],
    priority: 8,
  },
  {
    id: 'property_info',
    label: 'Brochure & Spec Sharing',
    description: 'Distribute floor plans, amenity lists, and location maps.',
    icon: 'doc',
    industries: ['real_estate'],
    supportedAgents: ['property_enquiry_agent'],
    priority: 8,
  },
  {
    id: 'sales_enquiries_re',
    label: 'Sales Enquiries',
    description: 'Qualify high-intent investors and route to senior brokers.',
    icon: 'dollar',
    industries: ['real_estate'],
    supportedAgents: ['property_enquiry_agent', 'lead_qualification_agent'],
    priority: 8,
  },

  // ── RETAIL ──────────────────────────────────────────────────
  {
    id: 'product_questions',
    label: 'Product Questions',
    description: 'Answer customer queries regarding specifications, sizes, and stock.',
    icon: 'bag',
    industries: ['retail'],
    supportedAgents: ['sales_assistant', 'customer_support_agent'],
    priority: 10,
  },
  {
    id: 'customer_support_retail',
    label: 'Customer Support',
    description: 'Handle returns, exchanges, refunds, and order tracking inquiries.',
    icon: 'support',
    industries: ['retail'],
    supportedAgents: ['customer_support_agent'],
    priority: 10,
  },
  {
    id: 'order_enquiries',
    label: 'Order Status & Tracking',
    description: 'Provide instant updates on shipping, tracking, and delivery dates.',
    icon: 'doc',
    industries: ['retail'],
    supportedAgents: ['customer_support_agent'],
    priority: 9,
  },
  {
    id: 'lead_capture_retail',
    label: 'Lead & Contact Capture',
    description: 'Capture shopper details for bulk orders, VIP clubs, and discount alerts.',
    icon: 'funnel',
    industries: ['retail'],
    supportedAgents: ['sales_assistant', 'lead_qualification_agent'],
    priority: 9,
  },
  {
    id: 'product_recommendations',
    label: 'Product Recommendations',
    description: 'Suggest complementary products and guide pre-purchase choices.',
    icon: 'star',
    industries: ['retail'],
    supportedAgents: ['sales_assistant'],
    priority: 8,
  },
  {
    id: 'sales_support_retail',
    label: 'Sales Assistance',
    description: 'Help shoppers overcome purchase hesitations and reduce cart abandonment.',
    icon: 'dollar',
    industries: ['retail'],
    supportedAgents: ['sales_assistant'],
    priority: 8,
  },
  {
    id: 'retail_followups',
    label: 'Follow-ups & Re-engagement',
    description: 'Follow up on abandoned queries and send seasonal promotions.',
    icon: 'phone',
    industries: ['retail'],
    supportedAgents: ['sales_assistant', 'customer_support_agent'],
    priority: 7,
  },
  {
    id: 'store_info',
    label: 'Store Locations & Hours',
    description: 'Provide outlet locations, store timings, and parking details.',
    icon: 'map',
    industries: ['retail'],
    supportedAgents: ['customer_support_agent'],
    priority: 7,
  },

  // ── TECHNOLOGY ──────────────────────────────────────────────
  {
    id: 'customer_support_tech',
    label: 'Customer Support',
    description: 'Resolve common user questions and troubleshoot basic account queries.',
    icon: 'support',
    industries: ['technology'],
    supportedAgents: ['customer_support_agent', 'product_support_agent'],
    priority: 10,
  },
  {
    id: 'product_enquiries_tech',
    label: 'Product Enquiries',
    description: 'Explain software features, capabilities, and compatibility.',
    icon: 'doc',
    industries: ['technology'],
    supportedAgents: ['product_support_agent', 'sales_dev_agent'],
    priority: 10,
  },
  {
    id: 'ticket_routing',
    label: 'Technical Enquiry Routing',
    description: 'Triage incoming bug reports and route to engineering teams.',
    icon: 'chat',
    industries: ['technology'],
    supportedAgents: ['product_support_agent', 'customer_support_agent'],
    priority: 9,
  },
  {
    id: 'lead_qual_tech',
    label: 'Lead Qualification',
    description: 'Screen inbound prospects by company size, use case, and budget.',
    icon: 'funnel',
    industries: ['technology'],
    supportedAgents: ['sales_dev_agent'],
    priority: 9,
  },
  {
    id: 'sales_enquiries_tech',
    label: 'Sales & Enterprise Enquiries',
    description: 'Handle custom tier pricing, security reviews, and SLA requests.',
    icon: 'dollar',
    industries: ['technology'],
    supportedAgents: ['sales_dev_agent'],
    priority: 8,
  },
  {
    id: 'demo_booking_tech',
    label: 'Product Demo Booking',
    description: 'Schedule live software walkthroughs with product specialists.',
    icon: 'calendar',
    industries: ['technology'],
    supportedAgents: ['sales_dev_agent'],
    priority: 9,
  },
  {
    id: 'employee_support_tech',
    label: 'Internal Employee Support',
    description: 'Assist internal staff with company policies, IT access, and HR info.',
    icon: 'user',
    industries: ['technology'],
    supportedAgents: ['hr_support_agent'],
    priority: 7,
  },
  {
    id: 'tech_followups',
    label: 'Prospect Follow-ups',
    description: 'Automate post-demo follow-ups and trial onboarding check-ins.',
    icon: 'phone',
    industries: ['technology'],
    supportedAgents: ['sales_dev_agent'],
    priority: 8,
  },

  // ── PROFESSIONAL SERVICES ───────────────────────────────────
  {
    id: 'client_enquiries',
    label: 'Client Enquiries',
    description: 'Receive and qualify incoming inquiries for legal, accounting, or consulting.',
    icon: 'chat',
    industries: ['professional_services'],
    supportedAgents: ['client_enquiry_agent', 'customer_support_agent'],
    priority: 10,
  },
  {
    id: 'appointment_booking_prof',
    label: 'Appointment Booking',
    description: 'Schedule client meetings and consultation slots directly into calendars.',
    icon: 'calendar',
    industries: ['professional_services'],
    supportedAgents: ['appointment_coordinator', 'client_enquiry_agent'],
    priority: 10,
  },
  {
    id: 'lead_capture_prof',
    label: 'Lead Capture',
    description: 'Capture project scopes, client details, and initial requirements.',
    icon: 'funnel',
    industries: ['professional_services'],
    supportedAgents: ['client_enquiry_agent', 'lead_qualification_agent'],
    priority: 9,
  },
  {
    id: 'consultation_requests',
    label: 'Consultation Requests',
    description: 'Screen advisory requests and match with senior partners.',
    icon: 'user',
    industries: ['professional_services'],
    supportedAgents: ['client_enquiry_agent', 'appointment_coordinator'],
    priority: 9,
  },
  {
    id: 'prof_followups',
    label: 'Client Follow-ups',
    description: 'Automate proposal follow-ups and engagement confirmations.',
    icon: 'phone',
    industries: ['professional_services'],
    supportedAgents: ['client_enquiry_agent', 'lead_qualification_agent'],
    priority: 8,
  },
  {
    id: 'service_info_prof',
    label: 'Service Information',
    description: 'Share practice area overviews, capability decks, and FAQs.',
    icon: 'doc',
    industries: ['professional_services'],
    supportedAgents: ['client_enquiry_agent'],
    priority: 8,
  },
  {
    id: 'client_support_prof',
    label: 'Ongoing Client Support',
    description: 'Handle billing FAQs, document requests, and client intake.',
    icon: 'support',
    industries: ['professional_services'],
    supportedAgents: ['client_enquiry_agent', 'customer_support_agent'],
    priority: 7,
  },

  // ── OTHER / GENERAL ─────────────────────────────────────────
  {
    id: 'general_enquiries',
    label: 'General Customer Enquiries',
    description: 'Answer common questions about your services, timings, and operations.',
    icon: 'chat',
    industries: ['other'],
    supportedAgents: ['business_assistant', 'customer_support_agent'],
    priority: 10,
  },
  {
    id: 'general_lead_capture',
    label: 'Lead & Contact Capture',
    description: 'Capture prospective customer info and qualify incoming requests.',
    icon: 'funnel',
    industries: ['other'],
    supportedAgents: ['business_assistant', 'lead_qualification_agent'],
    priority: 10,
  },
  {
    id: 'general_booking',
    label: 'Appointment & Meeting Booking',
    description: 'Schedule consultations, calls, and service appointments.',
    icon: 'calendar',
    industries: ['other'],
    supportedAgents: ['appointment_coordinator', 'business_assistant'],
    priority: 9,
  },
  {
    id: 'general_support',
    label: '24/7 Customer Support',
    description: 'Provide round-the-clock responses to routine customer inquiries.',
    icon: 'support',
    industries: ['other'],
    supportedAgents: ['customer_support_agent', 'business_assistant'],
    priority: 8,
  },
  {
    id: 'general_info',
    label: 'Service & Pricing Information',
    description: 'Share service packages, pricing estimates, and process overviews.',
    icon: 'dollar',
    industries: ['other'],
    supportedAgents: ['business_assistant'],
    priority: 8,
  },
  {
    id: 'general_followups',
    label: 'Automated Client Follow-ups',
    description: 'Send timely reminders and follow up with interested prospects.',
    icon: 'phone',
    industries: ['other'],
    supportedAgents: ['business_assistant'],
    priority: 8,
  },
  {
    id: 'workflow_automation',
    label: 'Custom Workflow Automation',
    description: 'Automate repetitive communication tasks tailored to your specific process.',
    icon: 'star',
    industries: ['other'],
    supportedAgents: ['business_assistant'],
    priority: 7,
  },
];

export function getNeedsForIndustry(industryId: string): BusinessNeed[] {
  const matched = businessNeedsCatalog.filter((need) =>
    need.industries.includes(industryId)
  );

  if (matched.length > 0) return matched;
  return businessNeedsCatalog.filter((need) => need.industries.includes('other'));
}
